### ISSUE TITLE
CREATE Navbar

### ISSUE THREAD

**Issue by Pinaka-Pani-18** [Pinaka-Pani-18/Contributors-Gallery#1]
**Description:**

Create a navigation bar with the following elements:
- Logo
- Dark mode button
- GitHub repository link

**Tasks:**

- [ ] Add Logo or Text as of now.
- [ ] Add a dark mode button to the navigation bar.
- [ ] Include a link to the GitHub repository in the navigation bar.

**Comment by DavidRod1865** [comment]
I would like to work on this if it still open.
